### ISSUE TITLE
Not supported

### ISSUE THREAD

**Issue by gilbertbw** [swider/express-dust#3]
When installing I get this error:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Gilbert>cd webstormprojects/maths4me

C:\Users\Gilbert\WebstormProjects\maths4me>npm install express-dust
npm http GET http://85.10.209.91/express-dust
npm http 200 http://85.10.209.91/express-dust
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: expre
ss-dust@0.1.4
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-dust"
npm ERR! cwd C:\Users\Gilbert\WebstormProjects\maths4me
npm ERR! node -v v0.8.1
npm ERR! npm -v 1.1.33
npm ERR! code EBADPLATFORM
npm ERR! message Unsupported
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Gilbert\WebstormProjects\maths4me\npm-debug.log
npm ERR! not ok code 0

C:\Users\Gilbert\WebstormProjects\maths4me>
```

**Comment by swider** [comment]
I don't currently have a Windows environment set up with node to test, can you pull the repo and see if it runs properly? This is probably just a matter of adding "win32" to the os array in package.json - or maybe removing the os line entirely

**Comment by gilbertbw** [comment]
I have forked, ran npm install, it installed linkedin-dust and express, I than ran the example app and got this error:

```
Error: Cannot find module 'undefined'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at new View (C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\node_modules\express\lib\view.js:42:49)
    at Function.app.render (C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\node_modules\express\lib\application.js:486:12)
    at ServerResponse.res.render (C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\node_modules\express\lib\response.js:677:7)
    at C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\examples\server.js:11:9
    at callbacks (C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\node_modules\express\lib\router\index.js:165:11)
    at param (C:\Users\Gilbert\WebstormProjects\maths4me\node_modules\express-dust\node_modules\express\lib\router\index.js:139:11)
```

What version of express do you use?

**Comment by swider** [comment]
I'm on 2.5.8, I've not tried other versions.

**Comment by cfjedimaster** [comment]
I just tried it and it worked fine. I can't seem to use it in app.engine('.html', require('express-dust').__express); yet, but I was able to do test=require('express-dust'); w/o error.

**Comment by cfjedimaster** [comment]
Ok I stand corrected. I read your docs on how to actually use it, and when I do, I get the same error as gilbertbw.
